version: '2'

services:
  master:
    image: p4km9y/hadoop-master
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "hadoop-master"
  slave1:
    image: p4km9y/hadoop-slave
    container_name: "slave1"
    ports:
      - "9901:9864"
      - "8041:8042"
  slave2:
    image: p4km9y/hadoop-slave
    container_name: "slave2"
    ports:
      - "9902:9864"
      - "8042:8042"
